# Copyright (c) 2018 Stig Rune Sellevag. All rights reserved.
# Released under the MIT license.

language: cpp
sudo: required
notifications:
  email: true

# Use Linux unless specified otherwise
os: linux
dist: trusty
ruby: 2.3.4

matrix:
  include:
    ############################################################################
    # GCC on GNU/Linux
    ############################################################################
    - os: linux
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gfortran
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && BUILD_TYPE=Debug"

    - os: linux
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gfortran
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && BUILD_TYPE=Release"

    - os: linux
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gfortran
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && BUILD_TYPE=Debug"

    - os: linux
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gfortran
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && BUILD_TYPE=Release"

    ############################################################################
    # Clang on GNU/Linux
    ############################################################################
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - g++-6
            - gfortran
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0 && BUILD_TYPE=Debug"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - g++-6
            - gfortran
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0 && BUILD_TYPE=Release"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - ${CXX} --version

  # Travis machines have 2 cores
  - JOBS=2

  # Install OpenBLAS
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      BLAS_URL="https://anaconda.org/conda-forge/openblas/0.3.3/download/linux-64/openblas-0.3.3-ha44fe06_1.tar.bz2"
      mkdir /opt/openblas
      travis_retry wget -qO- ${BLAS_URL} | tar jxv -C /opt/openblas
    fi
   
  # Have CMake to generate build files
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  
script:
  # Build and run tests
  - cmake --build . --config $BUILD_TYPE -- -j${JOBS}
  - ctest -C $BUILD_TYPE --output-on-failure -j${JOBS}
